
insert into categoria (nombre) values ( 'Comida');
insert into categoria (nombre) values ( 'Bebida');
insert into categoria (nombre) values ( 'Complementos');

insert into producto (nombre, precio, categoria_id) values ( 'Juice - Orange, Concentrate', 91, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Beef - Ground, Extra Lean, Fresh', 87, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Cheese - Parmesan Grated', 39, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Cups 10oz Trans', 67, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Wine - Beringer Founders Estate', 27, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Bread - Wheat Baguette', 82, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Quail - Eggs, Fresh', 3, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Cheese - Mascarpone', 97, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Mace', 25, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Oil - Shortening - All - Purpose', 63, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Marjoram - Fresh', 60, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Turnip - White', 74, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Pork Salted Bellies', 38, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Longos - Greek Salad', 15, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Amaretto', 85, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Godiva White Chocolate', 97, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Tomatoes - Roma', 61, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Oven Mitt - 13 Inch', 1, 3);
insert into producto (nombre, precio, categoria_id) values ( 'Vermouth - White, Cinzano', 72, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Club Soda - Schweppes, 355 Ml', 38, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Fenngreek Seed', 1, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Dill Weed - Dry', 72, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Pepper - Green', 56, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Bacardi Breezer - Tropical', 35, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Wine - Merlot Vina Carmen', 14, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Sauce - Black Current, Dry Mix', 9, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Crab - Soft Shell', 17, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Jameson Irish Whiskey', 19, 2);
insert into producto (nombre, precio, categoria_id) values ( 'Muffin Chocolate Individual Wrap', 77, 1);
insert into producto (nombre, precio, categoria_id) values ( 'Mussels - Frozen', 95, 1);